"""movies table

Revision ID: 1697b91bedf9
Revises: 
Create Date: 2017-12-20 10:16:14.535857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1697b91bedf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movieId', sa.String(length=7), nullable=True),
    sa.Column('EAN', sa.String(length=13), nullable=True),
    sa.Column('titleImdb', sa.String(length=64), nullable=True),
    sa.Column('titleOrig', sa.String(length=64), nullable=True),
    sa.Column('titleLocal', sa.String(length=64), nullable=True),
    sa.Column('medium', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_EAN'), 'movie', ['EAN'], unique=False)
    op.create_index(op.f('ix_movie_movieId'), 'movie', ['movieId'], unique=False)
    op.create_index(op.f('ix_movie_titleImdb'), 'movie', ['titleImdb'], unique=False)
    op.create_index(op.f('ix_movie_titleLocal'), 'movie', ['titleLocal'], unique=False)
    op.create_index(op.f('ix_movie_titleOrig'), 'movie', ['titleOrig'], unique=False)
    op.create_index(op.f('ix_movie_medium'), 'movie', ['medium'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_medium'), table_name='movie')
    op.drop_index(op.f('ix_movie_titleOrig'), table_name='movie')
    op.drop_index(op.f('ix_movie_titleLocal'), table_name='movie')
    op.drop_index(op.f('ix_movie_titleImdb'), table_name='movie')
    op.drop_index(op.f('ix_movie_movieId'), table_name='movie')
    op.drop_index(op.f('ix_movie_EAN'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
