"""critics with common ratings count

Revision ID: 47d1fcf30490
Revises: c0fd78267635
Create Date: 2018-03-24 17:42:45.222507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d1fcf30490'
down_revision = 'c0fd78267635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('critic', sa.Column('common_ratings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('critic', 'common_ratings_count')
    # ### end Alembic commands ###
